trigger:
- main

pool: vinsontosh_agent_pool


steps:
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'vinsanserviceconnection'
    backendAzureRmStorageAccountName: 'vinsanstorageacc'
    backendAzureRmContainerName: 'vinsancontainer'
    backendAzureRmKey: 'vinsan.terraform.tfstate'
